MODEL_CODES = {
    "Lookup": "100",
    "OTP": "101",
    "Merchant": "200",
    "Outlet": "201",
    "Member": "202",
    "MerchantConfig": "203",
    "Classes": "204",
    "staff": "205",
    "sections": "206",
    "student": "207",
    "books": "208",
    "invoice": "209",
    "guardian": "210",
    "transaction_history": "211",
}

ROLE_BASED_PERMISSIONS = {
    "Merchant": [
        "api.add_classes",
        "api.change_classes",
        "api.delete_classes",
        "api.view_classes",
        "api.add_guardian",
        "api.change_guardian",
        "api.delete_guardian",
        "api.view_guardian",
        "api.add_invoice",
        "api.change_invoice",
        "api.view_invoice",
        "api.add_member",
        "api.change_member",
        "api.delete_member",
        "api.view_member",
        "api.add_merchantconfig",
        "api.change_merchantconfig",
        "api.delete_merchantconfig",
        "api.view_merchantconfig",
        "api.add_outlet",
        "api.change_outlet",
        "api.delete_outlet",
        "api.view_outlet",
        "api.add_section",
        "api.change_section",
        "api.delete_section",
        "api.view_section",
        "api.add_staff",
        "api.change_staff",
        "api.delete_staff",
        "api.view_staff",
        "api.add_staffandsection",
        "api.change_staffandsection",
        "api.delete_staffandsection",
        "api.view_staffandsection",
        "api.add_student",
        "api.change_student",
        "api.delete_student",
        "api.view_student",
        "api.add_subject",
        "api.change_subject",
        "api.delete_subject",
        "api.view_subject",
        "api.add_transactionhistory",
        "api.change_transactionhistory",
        "api.view_transactionhistory",
        "auth.add_permission",
        "auth.view_permission"
    ]
}