# Generated by Django 4.2.16 on 2025-04-30 16:18

import api.models.mixins.uid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'classes',
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=255)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mata_data', models.JSONField(blank=True, null=True)),
            ],
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('role', models.CharField(choices=[('staff', 'STAFF'), ('parent', 'PARENT'), ('teacher', 'TEACHER'), ('student', 'STUDENT'), ('merchant', 'MERCHANT'), ('principal', 'PRINCIPAL'), ('registrar', 'REGISTRAR')], default='student', max_length=20)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=True)),
                ('cnic', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('blood_group', models.CharField(max_length=3, null=True)),
                ('emergency_contact', models.CharField(max_length=10, null=True)),
                ('avatar', models.CharField(blank=True, max_length=256, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('primary_phone', models.CharField(max_length=10, null=True, verbose_name='Primary Phone')),
                ('registration_number', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'MembersRegister',
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=7)),
                ('code', models.CharField(editable=False, max_length=4, unique=True)),
                ('domain', models.CharField(max_length=55, unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=24)),
                ('section_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_sections', to='api.classes')),
            ],
            options={
                'db_table': 'sections',
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'permissions': [('can_undelete', 'Can undelete this object')],
                'abstract': False,
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.member')),
                ('occupation', models.CharField(max_length=255)),
            ],
            options={
                'permissions': [('can_undelete', 'Can undelete this object')],
                'abstract': False,
            },
            bases=('api.member',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.member')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'staff',
            },
            bases=('api.member',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.member')),
                ('father_name', models.CharField(max_length=128)),
                ('mother_name', models.CharField(max_length=128)),
                ('father_cnic', models.CharField(max_length=13)),
                ('b_form', models.CharField(max_length=128, null=True)),
                ('roll_number', models.CharField(editable=False, max_length=24, unique=True)),
            ],
            options={
                'permissions': [('can_undelete', 'Can undelete this object')],
                'abstract': False,
            },
            bases=('api.member',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, unique=True)),
                ('subject_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='api.classes')),
            ],
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='SectionStaffAndSubject',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('is_head', models.BooleanField(default=False)),
                ('staff_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_and_staff', to='api.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('code', models.CharField(editable=False, max_length=3)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='api.merchant')),
            ],
            options={
                'ordering': ['merchant', 'code'],
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='api.member')),
            ],
            options={
                'permissions': [('can_undelete', 'Can undelete this object')],
                'abstract': False,
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='MerchantConfig',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('config_type', models.CharField(choices=[('email', 'Email Configuration'), ('branding', 'Branding Configuration'), ('otp', 'OTP Configuration'), ('notification', 'Notification Settings'), ('other', 'Other Configuration')], help_text='Category of the configuration', max_length=50)),
                ('key', models.CharField(help_text='Configuration key', max_length=255)),
                ('value', models.TextField(help_text='Configuration value')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.merchant')),
            ],
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.AddField(
            model_name='member',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.merchant'),
        ),
        migrations.AddField(
            model_name='member',
            name='outlets',
            field=models.ManyToManyField(related_name='outlet_members', to='api.outlet'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='api.lookup')),
            ],
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.AddField(
            model_name='classes',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_classes', to='api.outlet'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['-created_at'], name='api_subject_created_c3c804_idx'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_students', to='api.guardian'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_students', to='api.section'),
        ),
        migrations.AddField(
            model_name='staff',
            name='books',
            field=models.ManyToManyField(related_name='staff_books', to='api.subject'),
        ),
        migrations.AddField(
            model_name='staff',
            name='section',
            field=models.ManyToManyField(related_name='staff_sections', through='api.SectionStaffAndSubject', to='api.section'),
        ),
        migrations.AddField(
            model_name='sectionstaffandsubject',
            name='section_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_and_sections', to='api.staff'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['-created_at'], name='sections_created_dcccc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'section_class')},
        ),
        migrations.AlterUniqueTogether(
            name='outlet',
            unique_together={('merchant', 'code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='merchantconfig',
            unique_together={('merchant', 'config_type', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='merchant',
            unique_together={('name', 'owner', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'merchant', 'role', 'cnic')},
        ),
        migrations.AlterUniqueTogether(
            name='lookup',
            unique_together={('name', 'type')},
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_invoices', to='api.guardian'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='students',
            field=models.ManyToManyField(related_name='student_invoices', to='api.student'),
        ),
        migrations.AddField(
            model_name='classes',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_sections', to='api.staff'),
        ),
        migrations.AddIndex(
            model_name='sectionstaffandsubject',
            index=models.Index(fields=['-created_at'], name='api_section_created_2c5db7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='api_invoice_created_d9907c_idx'),
        ),
        migrations.AddIndex(
            model_name='classes',
            index=models.Index(fields=['-created_at'], name='classes_created_452d59_idx'),
        ),
    ]
