# Generated by Django 4.2.16 on 2025-05-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='books',
        ),
        migrations.AlterField(
            model_name='member',
            name='religion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
