# Generated by Django 4.2.16 on 2024-10-18 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_merchantmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmember',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.merchant'),
        ),
        migrations.AlterField(
            model_name='merchantmember',
            name='outlets',
            field=models.ManyToManyField(related_name='members', to='api.outlet'),
        ),
        migrations.AlterField(
            model_name='merchantmember',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
