# Generated by Django 4.2.16 on 2025-04-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classes_meta_data_invoice_meta_data_lookup_meta_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookup',
            options={},
        ),
        migrations.AlterField(
            model_name='lookup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='lookup',
            unique_together={('name', 'type')},
        ),
    ]
