# Generated by Django 4.2.16 on 2025-05-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_staff_books_alter_member_religion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='title',
            new_name='name',
        ),
    ]
