# Generated by Django 4.2.16 on 2025-05-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_subject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(editable=False, max_length=24),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_section', 'roll_number')},
        ),
    ]
