# Generated by Django 4.2.16 on 2025-04-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lookup_options_alter_lookup_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_network',
        ),
        migrations.AddField(
            model_name='member',
            name='area',
            field=models.CharField(default='gulshan islam', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='ryk', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='sami', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='religion',
            field=models.CharField(default='islam', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='b_form',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
