# Generated by Django 4.2.16 on 2024-10-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_merchantmember_merchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='short_name',
            field=models.CharField(default='ips', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet',
            name='city',
            field=models.CharField(default='Rahim Yar khan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet',
            name='city_short_form',
            field=models.CharField(default='ryk', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet',
            name='province',
            field=models.CharField(default='punjab', max_length=100),
            preserve_default=False,
        ),
    ]
