# Generated by Django 4.2.16 on 2025-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_phone_member_primary_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('staff', 'STAFF'), ('parent', 'PARENT'), ('teacher', 'TEACHER'), ('student', 'STUDENT'), ('merchant', 'MERCHANT'), ('principal', 'PRINCIPAL'), ('registrar', 'REGISTRAR')], default='student', max_length=20),
        ),
    ]
