# Generated by Django 4.2.16 on 2024-10-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merchant_short_name_outlet_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlet',
            options={'ordering': ['merchant', 'code']},
        ),
        migrations.AlterUniqueTogether(
            name='outlet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='outlet',
            name='code',
            field=models.CharField(default='100', editable=False, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='outlet',
            unique_together={('merchant', 'code', 'name')},
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='city_short_form',
        ),
    ]
