# Generated by Django 4.2.16 on 2024-12-16 06:48

import api.models.mixins.uid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_outlet_options_alter_outlet_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='api.merchantmember')),
            ],
            options={
                'permissions': [('can_undelete', 'Can undelete this object')],
                'abstract': False,
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='MerchantConfig',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('config_type', models.CharField(choices=[('email', 'Email Configuration'), ('branding', 'Branding Configuration'), ('otp', 'OTP Configuration'), ('notification', 'Notification Settings'), ('other', 'Other Configuration')], help_text='Category of the configuration', max_length=50)),
                ('key', models.CharField(help_text='Configuration key', max_length=255)),
                ('value', models.TextField(help_text='Configuration value')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.merchant')),
            ],
            options={
                'unique_together': {('merchant', 'config_type', 'key')},
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
    ]
