# Generated by Django 4.2.16 on 2025-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='allowance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bonus',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
