# Generated by Django 4.2.16 on 2025-05-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendance_attendance_unique_student_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mobile_notification_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Notification Token'),
        ),
    ]
