# Generated by Django 4.2.16 on 2025-01-12 22:34

import api.models.mixins.uid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_otp_merchantconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'books',
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'classes',
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('merchantmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.merchantmember')),
                ('occupation', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'guardians',
            },
            bases=('api.merchantmember',),
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('books', models.ManyToManyField(related_name='sections', to='api.books')),
            ],
            options={
                'db_table': 'sections',
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
            ],
            options={
                'permissions': [('can_undelete', 'Can undelete this object')],
                'abstract': False,
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('merchantmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.merchantmember')),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(editable=False, max_length=255, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_section', to='api.sections')),
                ('student_guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_guardian', to='api.guardian')),
            ],
            options={
                'db_table': 'students',
            },
            bases=('api.merchantmember',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('merchantmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.merchantmember')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('books', models.ManyToManyField(related_name='staff_books', to='api.books')),
                ('section', models.ManyToManyField(related_name='staff_sections', to='api.sections')),
            ],
            options={
                'db_table': 'staff',
            },
            bases=('api.merchantmember',),
        ),
        migrations.AddField(
            model_name='sections',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.staff'),
        ),
        migrations.AddField(
            model_name='sections',
            name='section_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.classes'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('transaction_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.guardian')),
                ('students', models.ManyToManyField(related_name='invoices', to='api.student')),
            ],
            options={
                'db_table': 'invoices',
            },
            bases=(models.Model, api.models.mixins.uid.UIDMixin),
        ),
        migrations.AddIndex(
            model_name='classes',
            index=models.Index(fields=['-created_at'], name='classes_created_452d59_idx'),
        ),
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['-created_at'], name='books_created_9e859d_idx'),
        ),
        migrations.AddIndex(
            model_name='sections',
            index=models.Index(fields=['-created_at'], name='sections_created_dcccc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sections',
            unique_together={('name', 'section_class')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='invoices_created_3daf52_idx'),
        ),
    ]
