# Generated by Django 4.2.16 on 2025-04-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_staff_allowance_alter_staff_basic_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='classes',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_sections', to='api.staff'),
        ),
    ]
