# Generated by Django 4.2.16 on 2025-04-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_section_coordinator_classes_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='allowance',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bonus',
        ),
        migrations.AlterField(
            model_name='member',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
