# Generated by Django 4.2.16 on 2025-01-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_books_classes_guardian_sections_transactionhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_classes', to='api.outlet'),
        ),
    ]
